# Generated by Django 3.0.5 on 2020-04-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('chass_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('car_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taycan.cars')),
            ],
        ),
    ]
